---
- name: When and Loops
  hosts: localhost
  vars:
    names_list:
      - Chad
      - Damian
      - Jason

  tasks:
    - name: Print that only YOUR name is awesome
      debug:
        msg: "{{ item }} is awesome!"
      loop: "{{ names_list }}"
      # CHALLENGE: Add a `when` condition here that this task only prints out YOUR name as awesome :)
      #when: names_list == " Damian"
      when: item == "Damian"
